routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::namespace('admin')->prefix('eshop-admin')->middleware('auth','role')->group(function ()
{
    Route::get('/', function (){
        return view('home');
    });
    Route::resource('/category', 'CategoryController');
    Route::resource('/products', 'ProductController');
    Route::resource('/slider', 'SliderController');
    Route::post('/slider/update-order', 'SliderController@change_image_order');
});

Route::get('/', 'FrontController')->name('index');

Route::get('products', 'ProductListController@allProducts')->name('products');

Route::get('product/{id}', 'ProductListController@singleProduct')->name('product');

Route::get('category/{id}', 'ProductListController@categories')->name('category');

Route::post('comment', 'ProductListController@addComment')->name('comment');

Route::get('/search', 'ProductListController@search')->name('search');

Route::get('/chart', 'ChartController@index')->name('chart')->middleware('auth');

Route::post('/add-to-cart', 'ChartController@add')->name('add-to-cart');

Route::post('/hide-product', 'ChartController@hide_product')->name('hide_product');

Route::post('/avatar', 'ChartController@changeAvatar')->name('change_avatar');

resources/views/admin/category-add.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6 d-flex align-items-stretch grid-margin">
            <div class="row flex-grow">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">CATEGORY</h4>
                            <p class="card-description">
                                CATEGORY TITLE
                            </p>
                            <form class="forms-sample " action="{{route('category.store')}} " method="post">
                                @csrf
                                <div class="form-group">
                                    <input type="text" class="form-control" name="title" placeholder="Enter title">
                                </div>
                                <button type="submit" class="btn btn-success mr-2">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category-edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6 d-flex align-items-stretch grid-margin">
            <div class="row flex-grow">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">CATEGORY</h4>
                            <p class="card-description">
                                CATEGORY TITLE
                            </p>
                            <form class="forms-sample " action="{{route('category.update',$category->id )}} " method="post">
                                @csrf
                                @method ('put')
                                <div class="form-group">
                                    <input type="text" class="form-control" name="title" value="{{$category->title}}" placeholder="Enter title">
                                </div>
                                <button type="submit" class="btn btn-success mr-2">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category-list.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Category List</h4>
                    <p class="card-description">
                        <a href="{{route('category.create')}}" class="btn btn-success">Add Category list</a>
                    </p>
                    <table class="table table-dark">
                        <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                Created At
                            </th>
                            <th>
                                Updated At
                            </th>
                            <th>
                                Sount
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                            @if(isset($categories)&& is_object($categories))
                            @foreach($categories as $key=> $category)
                        <tr>
                            <td>
                                {{++$key}}
                            </td>
                            <td>
                                {{$category->title}}
                            </td>
                            <td>
                                {{$category->created_at}}
                            </td>
                            <td>
                                {{$category->updated_at}}
                            </td>
                            <td>
                                {{$category->product->count()}}
                            </td>
                            <td>
                                <a href="{{route('category.edit',$category->id)}}" class="btn btn-primary">Edit</a>
                                <form action="{{route('category.destroy', $category->id )}}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger">Delete</button>


                                </form>
                            </td>
                        </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                    <div >{{$categories->links()}}</div>
                </div>

            </div>
    </div>
@endsection

resources/views/admin/product-add.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-12 d-flex align-items-stretch grid-margin">
            <div class="row flex-grow">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">PRODUCT</h4>
                            <h3 class="card-description">
                                PRODUCT TITLE
                            </h3>
                            <form class="forms-sample " action="{{route('products.store')}} " method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <p>Product Name</p>
                                    <input type="text" class="form-control" name="title" placeholder="add new Product">
                                </div>
                                <div class="form-group">
                                    <p>Availability</p>
                                    <select class="custom-select" name="availability" >

                                        <option value="1">Yes</option>
                                        <option value="0">No</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <p>Condition</p>
                                    <select class="custom-select"  name="condition" id="" >
                                        <option value="1">New</option>
                                        <option value="0">Old</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <p>Quantity</p>
                                    <input type="number" class="form-control" name="quantity" placeholder="Add quantity">
                                </div>
                                <div class="form-group">
                                    <p>Price</p>
                                    <input type="number" class="form-control" name="price" placeholder="add price">
                                </div>
                                <div class="form-group">
                                    <p>Web_id</p>
                                    <input type="text" class="form-control" name="web_id" placeholder="add web_id">
                                </div>
                                <div class="form-group">
                                    <p>Posters</p>
                                    <input type="file" class="form-control" name="posters[]" placeholder="add posters" multiple >
                                </div>
                                <div class="form-group">
                                    <p>Category</p>
                                    <select class="custom-select"  name="category_id" id="" >
                                        @foreach($categories as $category)
                                           <option value="{{$category->id}}">{{$category->title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-success mr-2">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/product-edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-12 d-flex align-items-stretch grid-margin">
            <div class="row flex-grow">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">PRODUCT</h4>
                            <h3 class="card-description">
                                PRODUCT TITLE
                            </h3>
                            <form class="forms-sample " action="{{route('products.update',$product->id)}} " method="post" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <p>Product Name</p>
                                    <input type="text" class="form-control" name="title" value="{{$product->title}}" placeholder="add new Product">
                                </div>
                                <div class="form-group">
                                    <p>Availability</p>
                                    <select class="custom-select" name="availability"  >
                                        @if($product->availability == 1)
                                        <option selected  value="1">Yes</option>
                                        <option value="0">No</option>
                                            @else
                                            <option  value="1">Yes</option>
                                            <option selected value="0">No</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <p>Condition</p>
                                    <select class="custom-select"  name="condition"  >
                                        @if($product->availability == 1)
                                            <option selected value="1">New</option>
                                            <option value="0">Old</option>
                                        @else
                                            <option value="1">New</option>
                                            <option selected value="0">Old</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <p>Quantity</p>
                                    <input type="number" class="form-control" name="quantity" placeholder="Add quantity" value="{{$product->quantity}}">
                                </div>
                                <div class="form-group">
                                    <p>Price</p>
                                    <input type="number" class="form-control" name="price" placeholder="add price" value="{{$product->price}}">
                                </div>
                                <div class="form-group">
                                    <p>Web_id</p>
                                    <input type="text" class="form-control" name="web_id" placeholder="add web_id" value="{{$product->web_id}}">
                                </div>
                                <div class="form-group">
                                    <p>Posters</p>
                                    <input type="file" class="form-control" name="posters[]" placeholder="add posters" multiple >
                                </div>
                                <div class="form-group">
                                    <p>Category</p>
                                    <select class="custom-select"  name="category_id"  >
                                        @foreach($categories as $category)
                                            @if($product->category->id == $category->id )
                                            <option value="{{$category->id}}" selected>{{$category->title}}</option>
                                                @else
                                                <option value="{{$category->id}}">{{$category->title}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-success mr-2">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/product.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Product List</h4>
                    <p class="card-description">
                        <a href="{{route('products.create')}}" class="btn btn-success">Add Product</a>
                    </p>
                    <table class="table table-dark ">
                        <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                Availability
                            </th>
                            <th>
                                Condition
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                Web_id
                            </th>
                            <th>
                                Posters
                            </th>
                            <th>
                                Category
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(isset($products)&& is_object($products))
                            @foreach($products as $key=> $product)
                                <tr>
                                    <td>
                                        {{++$key}}
                                    </td>
                                    <td>
                                        {{$product->title}}
                                    </td>
                                    <td>

                                        @if($product->availability == 1)
                                            Yes
                                        @else
                                            No
                                        @endif

                                    </td>
                                    <td>

                                        @if($product->condition == 1)
                                            New
                                        @else
                                            Old
                                        @endif
                                    </td>
                                    <td>
                                        {{$product->quantity}}
                                    </td>
                                    <td>
                                        {{$product->price}}
                                    </td>
                                    <td>
                                        {{$product->web_id}}
                                    </td>
                                    <td>

                                        @foreach(json_decode($product->posters) as $name)
                                            <img src="{{asset('/images/'.$name)}}" alt="Img" >
                                        @endforeach
                                    </td>
                                    <td>
                                        {{$product->category->title}}
                                    </td>
                                    <td>
                                        <a href="{{route('products.edit',$product->id)}}" class="btn btn-primary">Edit</a>
                                        <form action="{{route('products.destroy', $product->id )}}" method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger">Delete</button>


                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>

                </div>

            </div>
        </div>
@endsection

resources/views/admin/slider-add.blade.php
@extends('layouts.app')

@section('title', 'Slider list')

@section('page-name', 'Add a new image to the carousel')

@section('content')
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <form action="{{ route('slider.store') }}" method="post" role="form" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="add-image">New image</label>
                    <input type="file" name="images[]" id="add-image" multiple class="filestyle" data-buttonBefore="true" data-buttonName="btn-primary">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Add images</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/slider-list.blade.php
@extends('layouts.app')

@section('style')
    <link href="{{ asset('css/jquery-ui.min.css') }}" rel="stylesheet">
@endsection

@section('title', 'Slider list')

@section('page-name', 'List of images of the carousel')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    You can organize images by simply dragging them, holding the mouse, not the right place
                    <a href="{{ route('slider.create') }}" class="btn btn-primary pull-right btn-sm" role="button"
                       style="margin: -5px;">Add new image</a>
                </div>
                <div class="panel-body" id="sortable">
                    @if(isset($images) && is_object($images))
                        @foreach($images as $image)
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                                <div class="thumbnail sort-thumbnail" data-sort-id="{{ $image->id }}" style="height: 150px; width: 100%;">
                                    <form action="{{ route('slider.destroy', ['id' => $image->id]) }}" method="post">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit">
                                            <span class="glyphicon glyphicon-remove-circle"></span>
                                        </button>
                                    </form>
                                    <img src="{{ asset('images') . '/' . $image->path }}" alt="{{ $image->path }}"
                                         style="height: 100%;width: 100%;" class="img-responsive">
                                </div>
                            </div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div id="load" data-sotr-order-image>
        <i class="fa fa-spinner fa-spin"></i>
    </div>
@endsection

@section('script')

    <script src="{{ asset('js/jquery-ui.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            // Slider sortable
            $('#sortable').sortable({
                cursor: 'move',
                stop: function () {
                    var result = $.map($('.sort-thumbnail'), function (n) {
                        return n.attributes[1].value;
                    });
                    console.log(result);
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    jQuery.ajax({
                        url: "/eshop-admin/slider/update-order",
                        method: 'POST',
                        data: {ids: result},
                        beforeSend: function () {
                            $('#load').addClass('load');
                        },
                        success: function (data) {
                            $('#load').removeClass('load');
                        }
                    });
                }
            });
            $('.sort-thumbnail').on('mousedown', function () {
                $(this).css({
                    'opacity': '0.5',
                    'border': '2px dashed red'
                });
            });
            $('.sort-thumbnail').on('mouseup', function () {
                $(this).css({
                    'opacity': '1',
                    'border': 'none'
                });
            });
            // Slider sortable
        });
    </script>
@endsection